# Generated by Django 4.1.7 on 2023-03-16 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0001_create_banks_and_currency_markets_exchanges_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='banks',
            name='bybit_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
