# Generated by Django 3.2.14 on 2022-09-25 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0008_auto_20220926_0258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bestbankexchangesupdates',
            name='bank',
        ),
    ]
