# Generated by Django 3.2.14 on 2022-10-24 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0011_auto_20220930_1426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intrabanksnotloopedexchangesupdates',
            name='bank',
        ),
        migrations.DeleteModel(
            name='IntraBanksNotLoopedExchanges',
        ),
        migrations.DeleteModel(
            name='IntraBanksNotLoopedExchangesUpdates',
        ),
    ]
