# Generated by Django 3.2.14 on 2022-10-24 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0013_banksexchangerates_currency_market'),
    ]

    operations = [
        migrations.AddField(
            model_name='banksexchangeratesupdates',
            name='currency_market',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='currency_market_rates_update', to='banks.currencymarkets'),
        ),
    ]
