# Generated by Django 3.2.14 on 2022-10-24 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0014_banksexchangeratesupdates_currency_market'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banksexchangeratesupdates',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank_rates_update', to='banks.banks'),
        ),
    ]
