# Generated by Django 3.2.14 on 2023-02-13 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_exchanges', '0047_auto_20230213_1849'),
        ('banks', '0016_banksexchangerates_unique_bank_exchanges'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankinvestexchangesupdates',
            name='currency_market',
        ),
        migrations.RemoveField(
            model_name='bestbankexchanges',
            name='bank',
        ),
        migrations.RemoveField(
            model_name='bestbankexchanges',
            name='update',
        ),
        migrations.RemoveField(
            model_name='intrabanksexchanges',
            name='bank',
        ),
        migrations.RemoveField(
            model_name='intrabanksexchanges',
            name='update',
        ),
        migrations.RemoveField(
            model_name='intrabanksexchangesupdates',
            name='bank',
        ),
        migrations.AlterField(
            model_name='banksexchangerates',
            name='price',
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name='currencymarkets',
            name='name',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='BankInvestExchanges',
        ),
        migrations.DeleteModel(
            name='BankInvestExchangesUpdates',
        ),
        migrations.DeleteModel(
            name='BestBankExchanges',
        ),
        migrations.DeleteModel(
            name='BestBankExchangesUpdates',
        ),
        migrations.DeleteModel(
            name='IntraBanksExchanges',
        ),
        migrations.DeleteModel(
            name='IntraBanksExchangesUpdates',
        ),
    ]
