# Generated by Django 3.2.14 on 2023-02-13 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0017_auto_20230213_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banksexchangerates',
            name='price',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
