# Generated by Django 4.1.7 on 2023-02-27 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0018_alter_banksexchangerates_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banks',
            name='binance_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='banks',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
