# Generated by Django 3.2.14 on 2022-10-05 16:37

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InfoLoop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.BooleanField(blank=True, default=None, null=True)),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='Update date')),
                ('all_banks_exchanges', models.DurationField(default=datetime.timedelta(0))),
                ('all_crypto_exchanges', models.DurationField(default=datetime.timedelta(0))),
                ('all_exchanges', models.DurationField(default=datetime.timedelta(0))),
            ],
        ),
    ]
