# Generated by Django 3.2.14 on 2022-08-12 00:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0005_alter_intrabanksnotloopedexchanges_analogous_exchange'),
        ('crypto_exchanges', '0002_Add_New'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterExchangesUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Update date')),
                ('duration', models.DurationField(default=datetime.timedelta(0))),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InterExchanges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_of_transfers', models.JSONField()),
                ('p2p_type', models.CharField(max_length=7)),
                ('marginality_percentage', models.FloatField(blank=True, default=None, null=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inter_exchanges', to='banks.banks')),
                ('crypto_exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inter_exchanges', to='crypto_exchanges.cryptoexchanges')),
                ('update', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datas', to='crypto_exchanges.interexchangesupdate')),
            ],
        ),
    ]
