# Generated by Django 3.2.14 on 2022-09-11 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_exchanges', '0004_auto_20220911_1931'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card2Fiat2CryptoExchanges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset', models.CharField(max_length=4)),
                ('fiat', models.CharField(max_length=3)),
                ('trade_type', models.CharField(max_length=4)),
                ('price', models.FloatField(blank=True, default=None, null=True)),
                ('crypto_exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_2_fiat_2_crypto_exchanges', to='crypto_exchanges.cryptoexchanges')),
                ('update', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datas', to='crypto_exchanges.card2fiat2cryptoexchangesupdates')),
            ],
        ),
        migrations.CreateModel(
            name='Card2CryptoExchanges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset', models.CharField(max_length=4)),
                ('fiat', models.CharField(max_length=3)),
                ('trade_type', models.CharField(max_length=4)),
                ('price', models.FloatField(blank=True, default=None, null=True)),
                ('crypto_exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_2_crypto_exchanges', to='crypto_exchanges.cryptoexchanges')),
                ('update', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datas', to='crypto_exchanges.card2cryptoexchangesupdates')),
            ],
        ),
    ]
