# Generated by Django 3.2.14 on 2022-09-11 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_exchanges', '0005_card2cryptoexchanges_card2fiat2cryptoexchanges'),
    ]

    operations = [
        migrations.AddField(
            model_name='card2fiat2cryptoexchanges',
            name='transaction_method',
            field=models.CharField(default=1, max_length=35),
            preserve_default=False,
        ),
    ]
