# Generated by Django 3.2.14 on 2022-09-15 11:14

import datetime

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_exchanges', '0006_card2fiat2cryptoexchanges_transaction_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListsFiatCryptoUpdates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Update date')),
                ('duration', models.DurationField(default=datetime.timedelta(0))),
                ('list_fiat_crypto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_fiat_crypto_update', to='crypto_exchanges.cryptoexchanges')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ListsFiatCrypto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_fiat_crypto', models.JSONField()),
                ('trade_type', models.CharField(max_length=4)),
                ('crypto_exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_fiat_crypto', to='crypto_exchanges.cryptoexchanges')),
                ('update', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datas', to='crypto_exchanges.listsfiatcryptoupdates')),
            ],
        ),
    ]
