# Generated by Django 3.2.14 on 2022-09-15 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_exchanges', '0007_listsfiatcrypto_listsfiatcryptoupdates'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listsfiatcrypto',
            old_name='list_fiat_crypto',
            new_name='list_fiat',
        ),
        migrations.AddField(
            model_name='listsfiatcrypto',
            name='asset',
            field=models.CharField(default=1, max_length=4),
            preserve_default=False,
        ),
    ]
