# Generated by Django 3.2.14 on 2022-09-17 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0005_alter_intrabanksnotloopedexchanges_analogous_exchange'),
        ('crypto_exchanges', '0011_auto_20220916_0210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='p2pcryptoexchangesrates',
            name='pay_type',
        ),
        migrations.AddField(
            model_name='p2pcryptoexchangesrates',
            name='bank',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='p2p_rates', to='banks.banks'),
            preserve_default=False,
        ),
    ]
