# Generated by Django 3.2.14 on 2022-09-19 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_exchanges', '0013_bestpaymentchannels_bestpaymentchannelsupdates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bestpaymentchannels',
            name='payment_channel_id',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
