# Generated by Django 3.2.14 on 2022-09-19 13:58

import datetime

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_exchanges', '0014_alter_bestpaymentchannels_payment_channel_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card2Wallet2CryptoExchanges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset', models.CharField(max_length=4)),
                ('fiat', models.CharField(max_length=3)),
                ('trade_type', models.CharField(max_length=4)),
                ('transaction_method', models.CharField(max_length=35)),
                ('price', models.FloatField(blank=True, default=None, null=True)),
                ('crypto_exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_2_wallet_2_crypto_exchanges', to='crypto_exchanges.cryptoexchanges')),
            ],
        ),
        migrations.CreateModel(
            name='Card2Wallet2CryptoExchangesUpdates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Update date')),
                ('duration', models.DurationField(default=datetime.timedelta(0))),
                ('crypto_exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_2_wallet_2_crypto_exchanges_update', to='crypto_exchanges.cryptoexchanges')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='card2fiat2cryptoexchangesupdates',
            name='crypto_exchange',
        ),
        migrations.DeleteModel(
            name='Card2Fiat2CryptoExchanges',
        ),
        migrations.DeleteModel(
            name='Card2Fiat2CryptoExchangesUpdates',
        ),
        migrations.AddField(
            model_name='card2wallet2cryptoexchanges',
            name='update',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datas', to='crypto_exchanges.card2wallet2cryptoexchangesupdates'),
        ),
    ]
