# Generated by Django 3.2.14 on 2022-09-19 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_exchanges', '0015_auto_20220919_1758'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bestpaymentchannels',
            old_name='payment_channel_id',
            new_name='exchange_rate_id',
        ),
    ]
