# Generated by Django 3.2.14 on 2022-09-20 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_exchanges', '0017_rename_exchange_rate_id_bestpaymentchannels_exchange_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bestpaymentchannels',
            name='price',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
