# Generated by Django 3.2.14 on 2022-09-21 23:13

import datetime

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0006_banks_binance_name'),
        ('crypto_exchanges', '0020_bestcombinationpaymentchannels_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterBankAndCryptoExchangesUpdates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Update date')),
                ('duration', models.DurationField(default=datetime.timedelta(0))),
                ('crypto_exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inter_bank_and_crypro_exchanges_update', to='crypto_exchanges.cryptoexchanges')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InterBankAndCryptoExchanges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_bank_rate', models.JSONField()),
                ('list_crypto_rate', models.JSONField()),
                ('marginality_percentage', models.FloatField(blank=True, default=None, null=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inter_bank_and_crypro_exchanges', to='banks.banks')),
                ('bank_rate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_rate_inter_bank_and_crypro_exchanges', to='banks.banksexchangerates')),
                ('crypto_exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inter_bank_and_crypro_exchanges', to='crypto_exchanges.cryptoexchanges')),
                ('crypto_rate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crypto_rates_inter_bank_and_crypro_exchanges', to='crypto_exchanges.bestcombinationpaymentchannels')),
                ('update', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datas', to='crypto_exchanges.interbankandcryptoexchangesupdates')),
            ],
        ),
    ]
