# Generated by Django 3.2.14 on 2022-10-03 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_exchanges', '0022_alter_interbankandcryptoexchanges_bank_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='card2wallet2cryptoexchanges',
            name='intra_crypto_exchange',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='card_2_wallet_2_crypto_exchange', to='crypto_exchanges.intracryptoexchanges'),
            preserve_default=False,
        ),
    ]
