# Generated by Django 3.2.14 on 2022-10-05 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_exchanges', '0024_card2wallet2cryptoexchanges_transaction_fee'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interbankandcryptoexchanges',
            options={'ordering': ['-marginality_percentage']},
        ),
    ]
