# Generated by Django 3.2.14 on 2022-10-06 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_exchanges', '0026_bestcombinationpaymentchannels_unique_currency_pair'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='bestcombinationpaymentchannels',
            name='unique_currency_pair',
        ),
        migrations.AddConstraint(
            model_name='bestcombinationpaymentchannels',
            constraint=models.UniqueConstraint(fields=('from_fiat', 'to_fiat', 'input_bank', 'output_bank'), name='unique_currency_pair'),
        ),
    ]
