# Generated by Django 3.2.14 on 2022-10-06 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_exchanges', '0028_auto_20221007_0247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interbankandcryptoexchanges',
            name='list_bank_rate',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
