version: '3.8'
services:

  tor_proxy:
    restart: always
    image: dockage/tor-privoxy:latest
    ports:
      - "9050:9050"
      - "9051:9051"
      - "8118:8118"

  redis:
    image: redis:latest

  db:
    image: postgres:13.9-alpine
    restart: always
    volumes:
      - db_arbitration:/var/lib/postgresql/data
    env_file:
      - .env

  arbitration:
    build:
      context: ../arbitration
    restart: always
    volumes:
      - static_value:/arbitration/static/
    depends_on:
      - db
      - tor_proxy
    env_file:
      - .env

  nginx:
    image: nginx:1.23.3-alpine
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_value:/var/html/static/
    depends_on:
      - arbitration

  celery:
    restart: always
    build:
      context: ../arbitration
    command: celery -A arbitration worker --concurrency=8 --loglevel=info --max-tasks-per-child=1
    env_file:
      - .env
    depends_on:
      - redis
      - arbitration


volumes:
  db_arbitration:
  static_value: