version: '3.9'
services:

  tor_proxy:
    image: dockage/tor-privoxy:latest
    container_name: tor_proxy
    hostname: tor_proxy
    restart: always
    ports:
      - "9050:9050"
      - "9051:9051"
      - "8118:8118"

  redis:
    restart: always
    image: redis:latest
    container_name: redis

  db:
    image: postgres:15.2-alpine
    container_name: db
    restart: always
    volumes:
      - db_arbitration:/var/lib/postgresql/data
    env_file:
      - .env

  arbitration:
    build:
      context: ../arbitration
    container_name: arbitration
    restart: always
    volumes:
      - static_value:/arbitration/static/
    depends_on:
      - db
    env_file:
      - .env

  nginx:
    image: nginx:1.23.3-alpine
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_value:/var/html/static/
    depends_on:
      - arbitration

  celery-parsing:
    restart: always
    build:
      context: ../arbitration
    container_name: celery-parsing
    entrypoint: celery
    command:  -A arbitration worker --loglevel=ERROR -Q parsing -c 7 -n parsing_worker
    env_file:
      - .env
    links:
      - redis
    depends_on:
      - arbitration
      - redis

  celery-calculating:
    restart: always
    build:
      context: ../arbitration
    container_name: celery-calculating
    entrypoint: celery
    command:  -A arbitration worker --loglevel=ERROR -Q calculating -c 2 -n calculating_worker
    env_file:
      - .env
    links:
      - redis
    depends_on:
      - arbitration
      - redis

  celery-beat:
    restart: always
    build:
      context: ../arbitration
    container_name: celery-beat
    entrypoint: celery
    command: -A arbitration beat --loglevel=ERROR
    env_file:
      - .env
    links:
      - celery-parsing
      - celery-calculating
      - redis
    depends_on:
      - celery-parsing
      - celery-calculating
      - redis
      - tor_proxy
      - nginx

volumes:
  db_arbitration:
  static_value: