# Generated by Django 4.1.7 on 2023-03-06 12:55

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoExchanges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='IntraCryptoExchangesRatesUpdates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Update date')),
                ('duration', models.DurationField(default=datetime.timedelta(0))),
                ('crypto_exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crypto_exchanges_update', to='crypto_exchanges.cryptoexchanges')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IntraCryptoExchangesRates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_asset', models.CharField(max_length=4)),
                ('to_asset', models.CharField(max_length=4)),
                ('price', models.FloatField()),
                ('spot_fee', models.FloatField(default=None)),
                ('crypto_exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crypto_exchanges', to='crypto_exchanges.cryptoexchanges')),
                ('update', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datas', to='crypto_exchanges.intracryptoexchangesratesupdates')),
            ],
        ),
        migrations.AddConstraint(
            model_name='intracryptoexchangesrates',
            constraint=models.UniqueConstraint(fields=('crypto_exchange', 'from_asset', 'to_asset'), name='unique_intra_crypto_exchanges'),
        ),
    ]
