# Generated by Django 4.1.7 on 2023-03-06 12:56

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0001_create_banks_and_currency_markets_exchanges_model'),
        ('crypto_exchanges', '0001_create_intra_crypto_exchanges_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoExchangesRatesUpdates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Update date')),
                ('duration', models.DurationField(default=datetime.timedelta(0))),
                ('payment_channel', models.CharField(blank=True, max_length=30, null=True)),
                ('bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crypto_exchange_rates_update', to='banks.banks')),
                ('crypto_exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crypto_exchange_rates_update', to='crypto_exchanges.cryptoexchanges')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CryptoExchangesRates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset', models.CharField(max_length=4)),
                ('fiat', models.CharField(max_length=3)),
                ('trade_type', models.CharField(max_length=4)),
                ('payment_channel', models.CharField(blank=True, max_length=30, null=True)),
                ('transaction_method', models.CharField(blank=True, max_length=30, null=True)),
                ('transaction_fee', models.FloatField(blank=True, default=None, null=True)),
                ('price', models.FloatField(blank=True, default=None, null=True)),
                ('pre_price', models.FloatField(blank=True, default=None, null=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crypto_exchange_rates', to='banks.banks')),
                ('crypto_exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crypto_exchange_rates', to='crypto_exchanges.cryptoexchanges')),
                ('intra_crypto_exchange', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='card_2_wallet_2_crypto_exchange_rates', to='crypto_exchanges.intracryptoexchangesrates')),
                ('update', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datas', to='crypto_exchanges.cryptoexchangesratesupdates')),
            ],
        ),
        migrations.AddConstraint(
            model_name='cryptoexchangesrates',
            constraint=models.UniqueConstraint(fields=('crypto_exchange', 'bank', 'asset', 'trade_type', 'fiat', 'transaction_method', 'payment_channel'), name='unique_crypto_exchange_rates'),
        ),
    ]
