# Generated by Django 3.2.14 on 2022-08-06 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_exchanges', '0001_Add_New'),
    ]

    operations = [
        migrations.RenameField(
            model_name='intracryptoexchanges',
            old_name='from_fiat',
            new_name='from_asset',
        ),
        migrations.RenameField(
            model_name='intracryptoexchanges',
            old_name='to_fiat',
            new_name='to_asset',
        ),
    ]
