# Generated by Django 4.1.7 on 2023-03-06 12:57

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_exchanges', '0002_create_crypto_exchanges_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListsFiatCryptoUpdates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Update date')),
                ('duration', models.DurationField(default=datetime.timedelta(0))),
                ('crypto_exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_fiat_crypto_update', to='crypto_exchanges.cryptoexchanges')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ListsFiatCrypto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_fiat_crypto', models.JSONField()),
                ('trade_type', models.CharField(max_length=4)),
                ('crypto_exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_fiat_crypto', to='crypto_exchanges.cryptoexchanges')),
                ('update', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datas', to='crypto_exchanges.listsfiatcryptoupdates')),
            ],
        ),
    ]
