# Generated by Django 4.1.7 on 2023-03-06 12:57

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0001_create_banks_and_currency_markets_exchanges_model'),
        ('crypto_exchanges', '0003_create_lists_fiats_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterExchangesUpdates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Update date')),
                ('duration', models.DurationField(default=datetime.timedelta(0))),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inter_exchanges_update', to='banks.banks')),
                ('crypto_exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inter_exchanges_update', to='crypto_exchanges.cryptoexchanges')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InterExchanges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marginality_percentage', models.FloatField(verbose_name='Marginality percentage')),
                ('diagram', models.CharField(blank=True, max_length=100, null=True)),
                ('dynamics', models.CharField(default=None, max_length=4, null=True)),
                ('new', models.BooleanField(default=True, null=True)),
                ('bank_exchange', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank_rate_inter_exchanges', to='banks.banksexchangerates')),
                ('crypto_exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inter_exchanges', to='crypto_exchanges.cryptoexchanges')),
                ('input_bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input_bank_inter_exchanges', to='banks.banks')),
                ('input_crypto_exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input_crypto_exchange_inter_exchanges', to='crypto_exchanges.cryptoexchangesrates')),
                ('interim_crypto_exchange', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interim_exchange_inter_exchanges', to='crypto_exchanges.intracryptoexchangesrates')),
                ('output_bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='output_bank_inter_exchanges', to='banks.banks')),
                ('output_crypto_exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='output_crypto_exchange_inter_exchanges', to='crypto_exchanges.cryptoexchangesrates')),
                ('second_interim_crypto_exchange', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second_interim_exchange_inter_exchanges', to='crypto_exchanges.intracryptoexchangesrates')),
                ('update', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datas', to='crypto_exchanges.interexchangesupdates')),
            ],
            options={
                'ordering': ['-marginality_percentage'],
            },
        ),
        migrations.AddConstraint(
            model_name='interexchanges',
            constraint=models.UniqueConstraint(fields=('crypto_exchange', 'input_bank', 'output_bank', 'input_crypto_exchange', 'interim_crypto_exchange', 'second_interim_crypto_exchange', 'output_crypto_exchange', 'bank_exchange'), name='unique_inter_exchanges'),
        ),
    ]
