# Generated by Django 4.1.7 on 2023-03-06 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_exchanges', '0004_create_inter_exchanges_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatedMarginalityPercentages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Update date')),
                ('marginality_percentage', models.FloatField(verbose_name='Marginality percentage')),
                ('inter_exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marginality_percentages', to='crypto_exchanges.interexchanges')),
            ],
        ),
    ]
