# Generated by Django 4.1.7 on 2023-03-06 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_exchanges', '0005_create_marginality_percentages_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='interexchangesupdates',
            name='ended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='interexchangesupdates',
            name='full_update',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='interexchangesupdates',
            name='international',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='interexchangesupdates',
            name='simpl',
            field=models.BooleanField(default=True),
        ),
    ]
