# Generated by Django 3.2.14 on 2022-09-15 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_exchanges', '0009_auto_20220915_1529'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listsfiatcryptoupdates',
            old_name='list_fiat_crypto',
            new_name='crypto_exchange',
        ),
    ]
