# Generated by Django 3.2.14 on 2022-09-15 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_exchanges', '0010_rename_list_fiat_crypto_listsfiatcryptoupdates_crypto_exchange'),
    ]

    operations = [
        migrations.AddField(
            model_name='card2cryptoexchanges',
            name='commission',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='card2cryptoexchanges',
            name='pre_price',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
