# Generated by Django 3.2.14 on 2022-09-19 11:38

import datetime

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0006_banks_binance_name'),
        ('crypto_exchanges', '0012_auto_20220917_1714'),
    ]

    operations = [
        migrations.CreateModel(
            name='BestPaymentChannelsUpdates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Update date')),
                ('duration', models.DurationField(default=datetime.timedelta(0))),
                ('crypto_exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='best_payment_channel_update', to='crypto_exchanges.cryptoexchanges')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BestPaymentChannels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset', models.CharField(max_length=4)),
                ('fiat', models.CharField(max_length=3)),
                ('trade_type', models.CharField(max_length=4)),
                ('payment_channel_model', models.CharField(max_length=30)),
                ('payment_channel_id', models.PositiveIntegerField(max_length=10000)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='best_payment_channel', to='banks.banks')),
                ('crypto_exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='best_payment_channel', to='crypto_exchanges.cryptoexchanges')),
                ('update', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datas', to='crypto_exchanges.bestpaymentchannelsupdates')),
            ],
        ),
    ]
