# Generated by Django 3.2.14 on 2022-09-19 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_exchanges', '0016_rename_payment_channel_id_bestpaymentchannels_exchange_rate_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bestpaymentchannels',
            old_name='exchange_rate_id',
            new_name='exchange_id',
        ),
    ]
