# Generated by Django 3.2.14 on 2022-09-20 23:44

import datetime

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0006_banks_binance_name'),
        ('crypto_exchanges', '0018_bestpaymentchannels_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='BestCombinationPaymentChannelsUpdates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Update date')),
                ('duration', models.DurationField(default=datetime.timedelta(0))),
                ('crypto_exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='best_combinations_payment_channels_update', to='crypto_exchanges.cryptoexchanges')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BestCombinationPaymentChannels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_fiat', models.CharField(max_length=3)),
                ('to_fiat', models.CharField(max_length=3)),
                ('crypto_exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='best_combinations_payment_channels', to='crypto_exchanges.cryptoexchanges')),
                ('input_bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input_bank_best_combinations_payment_channels', to='banks.banks')),
                ('input_exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input_exchange_best_combinations_payment_channels', to='crypto_exchanges.bestpaymentchannels')),
                ('interim_exchange', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interim_exchange_best_combinations_payment_channels', to='crypto_exchanges.intracryptoexchanges')),
                ('output_bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='output_bank_best_combinations_payment_channels', to='banks.banks')),
                ('output_exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='output_exchange_best_combinations_payment_channels', to='crypto_exchanges.bestpaymentchannels')),
                ('update', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datas', to='crypto_exchanges.bestcombinationpaymentchannelsupdates')),
            ],
        ),
    ]
