# Generated by Django 3.2.14 on 2022-09-20 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_exchanges', '0019_bestcombinationpaymentchannels_bestcombinationpaymentchannelsupdates'),
    ]

    operations = [
        migrations.AddField(
            model_name='bestcombinationpaymentchannels',
            name='price',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
