# Generated by Django 3.2.14 on 2022-10-03 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_exchanges', '0023_card2wallet2cryptoexchanges_intra_crypto_exchange'),
    ]

    operations = [
        migrations.AddField(
            model_name='card2wallet2cryptoexchanges',
            name='transaction_fee',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
