# Generated by Django 3.2.14 on 2022-10-06 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_exchanges', '0025_alter_interbankandcryptoexchanges_options'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='bestcombinationpaymentchannels',
            constraint=models.UniqueConstraint(fields=('from_fiat', 'to_fiat'), name='unique_currency_pair'),
        ),
    ]
