# Generated by Django 3.2.14 on 2022-10-24 10:52

import datetime

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0012_auto_20221024_1052'),
        ('crypto_exchanges', '0029_alter_interbankandcryptoexchanges_list_bank_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterExchanges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crypto_exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inter_exchanges', to='crypto_exchanges.cryptoexchanges')),
                ('input_bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input_bank_inter_exchanges', to='banks.banks')),
                ('input_crypto_exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input_crypto_exchange_inter_exchanges', to='crypto_exchanges.bestpaymentchannels')),
                ('interim_crypto_exchange', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interim_exchange_best_inter_exchanges', to='crypto_exchanges.intracryptoexchanges')),
                ('output_bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='output_bank_inter_exchanges', to='banks.banks')),
                ('output_crypto_exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='output_crypto_exchange_inter_exchanges', to='crypto_exchanges.bestpaymentchannels')),
            ],
        ),
        migrations.CreateModel(
            name='RelatedMarginalityPercentages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Update date')),
                ('marginality_percentage', models.FloatField(blank=True, default=None, null=True)),
                ('inter_exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marginality_percentages', to='crypto_exchanges.interexchanges')),
            ],
        ),
        migrations.CreateModel(
            name='InterExchangesUpdates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Update date')),
                ('duration', models.DurationField(default=datetime.timedelta(0))),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inter_exchanges_update', to='banks.banks')),
                ('crypto_exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inter_exchanges_update', to='crypto_exchanges.cryptoexchanges')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='interexchanges',
            name='update',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datas', to='crypto_exchanges.interexchangesupdates'),
        ),
    ]
