# Generated by Django 3.2.14 on 2022-10-24 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_exchanges', '0030_auto_20221024_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interexchanges',
            name='input_crypto_exchange',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input_crypto_exchange_inter_exchanges', to='crypto_exchanges.p2pcryptoexchangesrates'),
        ),
        migrations.AlterField(
            model_name='interexchanges',
            name='output_crypto_exchange',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='output_crypto_exchange_inter_exchanges', to='crypto_exchanges.p2pcryptoexchangesrates'),
        ),
    ]
