# Generated by Django 3.2.14 on 2022-10-24 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0015_alter_banksexchangeratesupdates_bank'),
        ('crypto_exchanges', '0031_auto_20221024_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='p2pcryptoexchangesrates',
            name='payment_channel',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='p2pcryptoexchangesrates',
            name='pre_price',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='p2pcryptoexchangesrates',
            name='transaction_fee',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='p2pcryptoexchangesrates',
            name='transaction_method',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
        migrations.AddField(
            model_name='p2pcryptoexchangesratesupdates',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p2p_rates_update', to='banks.banks'),
        ),
    ]
