# Generated by Django 3.2.14 on 2022-10-24 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_exchanges', '0032_auto_20221024_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='p2pcryptoexchangesratesupdates',
            name='payment_channel',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
