# Generated by Django 3.2.14 on 2022-10-24 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_exchanges', '0033_p2pcryptoexchangesratesupdates_payment_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='p2pcryptoexchangesrates',
            name='intra_crypto_exchange',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='card_2_wallet_2_crypto_exchange_rates', to='crypto_exchanges.intracryptoexchanges'),
        ),
    ]
