# Generated by Django 3.2.14 on 2022-10-25 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_exchanges', '0035_interexchanges_bank_exchange'),
    ]

    operations = [
        migrations.AddField(
            model_name='interexchanges',
            name='second_interim_crypto_exchange',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second_interim_exchange_inter_exchanges', to='crypto_exchanges.intracryptoexchanges'),
        ),
        migrations.AlterField(
            model_name='interexchanges',
            name='interim_crypto_exchange',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interim_exchange_inter_exchanges', to='crypto_exchanges.intracryptoexchanges'),
        ),
    ]
