# Generated by Django 3.2.14 on 2022-10-26 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_exchanges', '0037_auto_20221026_1935'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interexchanges',
            options={'ordering': ['-marginality_percentage']},
        ),
    ]
