# Generated by Django 3.2.14 on 2022-11-22 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_exchanges', '0039_alter_interexchanges_marginality_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='interexchanges',
            name='diagram',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
