# Generated by Django 3.2.14 on 2022-11-30 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_exchanges', '0040_interexchanges_diagram'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='bestcombinationpaymentchannels',
            name='unique_currency_pair',
        ),
        migrations.AddConstraint(
            model_name='p2pcryptoexchangesrates',
            constraint=models.UniqueConstraint(fields=('crypto_exchange', 'bank', 'asset', 'trade_type', 'fiat', 'transaction_method', 'payment_channel'), name='unique_currency_pair'),
        ),
    ]
