# Generated by Django 3.2.14 on 2022-11-30 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_exchanges', '0041_auto_20221130_1545'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='p2pcryptoexchangesrates',
            name='unique_currency_pair',
        ),
        migrations.AddConstraint(
            model_name='bestcombinationpaymentchannels',
            constraint=models.UniqueConstraint(fields=('from_fiat', 'to_fiat', 'input_bank', 'output_bank', 'crypto_exchange'), name='unique_currency_pair'),
        ),
        migrations.AddConstraint(
            model_name='p2pcryptoexchangesrates',
            constraint=models.UniqueConstraint(fields=('crypto_exchange', 'bank', 'asset', 'trade_type', 'fiat', 'transaction_method', 'payment_channel'), name='unique_p2p'),
        ),
    ]
