# Generated by Django 3.2.14 on 2022-11-30 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_exchanges', '0042_auto_20221130_1546'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='interexchanges',
            constraint=models.UniqueConstraint(fields=('crypto_exchange', 'input_bank', 'output_bank', 'input_crypto_exchange', 'interim_crypto_exchange', 'second_interim_crypto_exchange', 'output_crypto_exchange', 'bank_exchange'), name='unique_inter_exchanges'),
        ),
    ]
