# Generated by Django 3.2.14 on 2022-11-30 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_exchanges', '0043_interexchanges_unique_inter_exchanges'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='intracryptoexchanges',
            constraint=models.UniqueConstraint(fields=('crypto_exchange', 'from_asset', 'to_asset'), name='unique_intra_crypto_exchanges'),
        ),
    ]
