# Generated by Django 3.2.14 on 2022-12-01 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_exchanges', '0044_intracryptoexchanges_unique_intra_crypto_exchanges'),
    ]

    operations = [
        migrations.AddField(
            model_name='intracryptoexchanges',
            name='spot_fee',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
