# Generated by Django 3.2.14 on 2023-02-07 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_exchanges', '0045_intracryptoexchanges_spot_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interexchanges',
            name='diagram',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
