# Generated by Django 4.1.7 on 2023-02-23 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_exchanges', '0047_auto_20230213_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='interexchanges',
            name='dynamics',
            field=models.CharField(default=None, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='interexchanges',
            name='new',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
