# Generated by Django 3.2.14 on 2022-07-14 21:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UsdtRub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy', models.FloatField()),
                ('sell', models.FloatField()),
                ('pay_types', models.CharField(choices=[('', ''), ('Tinkoff', 'Tinkoff')], max_length=10)),
                ('updated', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата обновления')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usdt_rub', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UsdtEur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy', models.FloatField()),
                ('sell', models.FloatField()),
                ('pay_types', models.CharField(choices=[('', ''), ('Tinkoff', 'Tinkoff')], max_length=10)),
                ('updated', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата обновления')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usdt_eur', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
