# Generated by Django 3.2.14 on 2022-08-01 13:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BinanceUpdates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Update date')),
                ('duration', models.DurationField(default=datetime.timedelta(0))),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BinanceExchanges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset', models.CharField(max_length=4)),
                ('fiat', models.CharField(max_length=3)),
                ('trade_type', models.CharField(max_length=4)),
                ('pay_type', models.CharField(max_length=16)),
                ('price', models.FloatField(blank=True, default=None, null=True)),
                ('update', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datas', to='p2p_exchanges.binanceupdates')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
