# Generated by Django 3.2.14 on 2022-08-02 17:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InsideWiseUpdates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Update date')),
                ('duration', models.DurationField(default=datetime.timedelta(0))),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InsideWiseExchanges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_of_transfers', models.JSONField()),
                ('marginality_percentage', models.FloatField(blank=True, default=None, null=True)),
                ('update', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datas', to='calculations.insidewiseupdates')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
