# Generated by Django 3.2.14 on 2022-07-15 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='P2P',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset', models.CharField(choices=[('USDT', 'USDT'), ('BUSD', 'BUSD'), ('BTC', 'BTC')], max_length=4)),
                ('trade_type', models.CharField(choices=[('BUY', 'buy'), ('SELL', 'sell')], max_length=4)),
                ('fiat', models.CharField(choices=[('RUB', 'rub'), ('USD', 'usd'), ('EUR', 'eur')], max_length=3)),
                ('pay_type', models.CharField(choices=[('Tinkoff', 'Tinkoff'), ('Wise', 'Wise'), ('RosBank', 'RosBank'), ('RUBfiatbalance', 'RUBfiatbalance')], max_length=15)),
                ('price', models.FloatField()),
            ],
        ),
    ]
