# Generated by Django 3.2.14 on 2022-07-15 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parses_p2p', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateP2P',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Update date')),
                ('duration', models.DurationField()),
            ],
        ),
        migrations.AddField(
            model_name='p2p',
            name='update',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='datas', to='parses_p2p.updatep2p'),
            preserve_default=False,
        ),
    ]
