# Generated by Django 3.2.14 on 2022-07-18 16:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parses_p2p', '0003_alter_updatep2pbinance_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updatep2pbinance',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
