# Generated by Django 3.2.14 on 2022-07-18 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parses_p2p', '0004_alter_updatep2pbinance_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='p2pbinance',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, default='2022-07-18 14:02:28.387199', verbose_name='Update date'),
            preserve_default=False,
        ),
    ]
