# Generated by Django 3.2.14 on 2022-07-29 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parses_p2p', '0007_auto_20220721_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='p2pbinance',
            name='pay_type',
            field=models.CharField(choices=[('Tinkoff', 'Tinkoff'), ('Wise', 'Wise'), ('RosBank', 'RosBank')], max_length=15),
        ),
    ]
