# Generated by Django 3.2.14 on 2022-07-29 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parses_p2p', '0008_Add_Abstract_Models_And_Tinkoff_Models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='p2pbinance',
            name='asset',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='p2pbinance',
            name='fiat',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='p2pbinance',
            name='pay_type',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='p2pbinance',
            name='trade_type',
            field=models.CharField(max_length=4),
        ),
    ]
