# Generated by Django 3.2.14 on 2022-07-31 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parses_p2p', '0009_Update_P2P_Parses_Model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='p2pbinance',
            name='pay_type',
            field=models.CharField(max_length=16),
        ),
    ]
