# Generated by Django 3.2.14 on 2022-08-06 16:25

import datetime

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IntraBanksExchangesUpdates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Update date')),
                ('duration', models.DurationField(default=datetime.timedelta(0))),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_exchanges_update', to='banks.banks')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IntraBanksExchanges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_of_transfers', models.JSONField()),
                ('marginality_percentage', models.FloatField(blank=True, default=None, null=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_exchanges', to='banks.banks')),
                ('update', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datas', to='banks.intrabanksexchangesupdates')),
            ],
        ),
        migrations.CreateModel(
            name='BanksExchangeRatesUpdates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Update date')),
                ('duration', models.DurationField(default=datetime.timedelta(0))),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_rates_update', to='banks.banks')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BanksExchangeRates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_fiat', models.CharField(max_length=3)),
                ('to_fiat', models.CharField(max_length=3)),
                ('price', models.FloatField(blank=True, default=None, null=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_rates', to='banks.banks')),
                ('update', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datas', to='banks.banksexchangeratesupdates')),
            ],
        ),
    ]
