# Generated by Django 3.2.14 on 2022-07-29 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0001_Add_Abstract_Models_And_Tinkoff_Models'),
    ]

    operations = [
        migrations.CreateModel(
            name='TinkoffExchanges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_fiats', models.CharField(max_length=3)),
                ('to_fiats', models.CharField(max_length=3)),
                ('price', models.FloatField(blank=True, default=None, null=True)),
            ],
            options={
                'db_table': 'TinkoffExchanges',
            },
        ),
    ]
