# Generated by Django 3.2.14 on 2022-08-11 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0002_Add_New'),
    ]

    operations = [
        migrations.AddField(
            model_name='intrabanksnotloopedexchanges',
            name='analogous_exchange',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='not_looped', to='banks.intrabanksexchanges'),
        ),
    ]
