# Generated by Django 3.2.14 on 2022-07-29 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0002_Add_Abstract_Models_And_Tinkoff_Models'),
    ]

    operations = [
        migrations.AddField(
            model_name='tinkoffexchanges',
            name='update',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tinkoffexchanges', to='banks.tinkoffupdates'),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='tinkoffexchanges',
            table=None,
        ),
        migrations.AlterModelTable(
            name='tinkoffupdates',
            table=None,
        ),
    ]
