# Generated by Django 3.2.14 on 2022-07-30 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0003_Add_Abstract_Models_And_Tinkoff_Models'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tinkoffexchanges',
            old_name='from_fiats',
            new_name='from_fiat',
        ),
        migrations.RenameField(
            model_name='tinkoffexchanges',
            old_name='to_fiats',
            new_name='to_fiat',
        ),
    ]
