# Generated by Django 3.2.14 on 2022-09-17 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0005_alter_intrabanksnotloopedexchanges_analogous_exchange'),
    ]

    operations = [
        migrations.AddField(
            model_name='banks',
            name='binance_name',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
