# Generated by Django 3.2.14 on 2022-07-31 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0006_Add_Wise'),
    ]

    operations = [
        migrations.AddField(
            model_name='tinkoffexchanges',
            name='updated',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Update date'),
        ),
        migrations.AddField(
            model_name='wiseexchanges',
            name='updated',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Update date'),
        ),
    ]
