# Generated by Django 3.2.14 on 2022-09-25 19:18

import datetime

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0006_banks_binance_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intrabanksnotloopedexchanges',
            name='bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_exchanges_not_looped', to='banks.banks'),
        ),
        migrations.AlterField(
            model_name='intrabanksnotloopedexchangesupdates',
            name='bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_exchanges_not_looped_update', to='banks.banks'),
        ),
        migrations.CreateModel(
            name='BankInvestExchangesUpdates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Update date')),
                ('duration', models.DurationField(default=datetime.timedelta(0))),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_invest_exchanges_update', to='banks.banks')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BankInvestExchanges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_fiat', models.CharField(max_length=3)),
                ('to_fiat', models.CharField(max_length=3)),
                ('price', models.FloatField(blank=True, default=None, null=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_invest_exchanges', to='banks.banks')),
                ('update', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datas', to='banks.bankinvestexchangesupdates')),
            ],
        ),
    ]
