# Generated by Django 3.2.14 on 2022-07-31 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0007_Add_Updated_To_BankExchangesModel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tinkoffexchanges',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='wiseexchanges',
            name='updated',
        ),
    ]
