# Generated by Django 3.2.14 on 2022-09-25 22:58

import datetime

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0007_auto_20220925_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='intrabanksnotloopedexchanges',
            name='from_fiat',
            field=models.CharField(default=1, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='intrabanksnotloopedexchanges',
            name='to_fiat',
            field=models.CharField(default=1, max_length=3),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='BestBankExchangesUpdates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Update date')),
                ('duration', models.DurationField(default=datetime.timedelta(0))),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='best_bank_exchanges_update', to='banks.banks')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BestBankExchanges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_fiat', models.CharField(max_length=3)),
                ('to_fiat', models.CharField(max_length=3)),
                ('price', models.FloatField(blank=True, default=None, null=True)),
                ('bank_exchange_model', models.CharField(max_length=30)),
                ('exchange_id', models.PositiveSmallIntegerField()),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='best_bank_exchanges', to='banks.banks')),
                ('update', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datas', to='banks.bestbankexchangesupdates')),
            ],
        ),
    ]
