# Generated by Django 3.2.14 on 2022-09-29 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0009_remove_bestbankexchangesupdates_bank'),
    ]

    operations = [
        migrations.AddField(
            model_name='banks',
            name='invest_name',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
