# Generated by Django 3.2.14 on 2022-09-30 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0010_banks_invest_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyMarkets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='intrabanksnotloopedexchanges',
            options={'ordering': ['-marginality_percentage']},
        ),
        migrations.RemoveField(
            model_name='bankinvestexchanges',
            name='bank',
        ),
        migrations.RemoveField(
            model_name='bankinvestexchangesupdates',
            name='bank',
        ),
        migrations.RemoveField(
            model_name='banks',
            name='invest_name',
        ),
        migrations.AddField(
            model_name='bankinvestexchanges',
            name='currency_market',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='currency_market_exchanges', to='banks.currencymarkets'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bankinvestexchangesupdates',
            name='currency_market',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='currency_market_exchanges_update', to='banks.currencymarkets'),
            preserve_default=False,
        ),
    ]
