# Generated by Django 4.1.7 on 2023-03-06 12:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InfoLoop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.BooleanField(default=False)),
                ('started', models.DateTimeField(auto_now_add=True, verbose_name='Started date')),
                ('stopped', models.DateTimeField(blank=True, null=True, verbose_name='Stopped date')),
                ('duration', models.DurationField(default=datetime.timedelta(0))),
            ],
            options={
                'ordering': ['-started'],
            },
        ),
    ]
