# Generated by Django 3.2.14 on 2022-11-24 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='infoloop',
            name='start_all_exchanges',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='infoloop',
            name='start_banks_exchanges',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='infoloop',
            name='start_crypto_exchanges',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
