# Generated by Django 3.2.14 on 2023-02-15 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20230215_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infoloop',
            name='count_of_rates',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
