# Generated by Django 4.1.7 on 2023-02-23 18:13

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_infoloop_count_of_rates'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='infoloop',
            options={'ordering': ['-started']},
        ),
        migrations.RenameField(
            model_name='infoloop',
            old_name='all_banks_exchanges',
            new_name='duration',
        ),
        migrations.RemoveField(
            model_name='infoloop',
            name='all_crypto_exchanges',
        ),
        migrations.RemoveField(
            model_name='infoloop',
            name='all_exchanges',
        ),
        migrations.RemoveField(
            model_name='infoloop',
            name='count_of_rates',
        ),
        migrations.RemoveField(
            model_name='infoloop',
            name='updated',
        ),
        migrations.AddField(
            model_name='infoloop',
            name='started',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 2, 23, 18, 13, 8, 429366, tzinfo=datetime.timezone.utc), verbose_name='Started date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='infoloop',
            name='stopped',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 23, 18, 13, 36, 715561, tzinfo=datetime.timezone.utc), verbose_name='Stopped date'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='infoloop',
            name='value',
            field=models.BooleanField(default=False),
        ),
    ]
