# Generated by Django 4.1.7 on 2023-02-23 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_infoloop_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infoloop',
            name='stopped',
            field=models.DateTimeField(null=True, verbose_name='Stopped date'),
        ),
    ]
